version: '3'

services:
  postgres:
    image: 'postgres:13.1-alpine'
    container_name: 'postgres-mancala'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'